### ISSUE TITLE
Project broken due to hearthstone Unity 5 update

### ISSUE THREAD

**Issue by Sembiance** [HearthSim/hearthstonejson#11]
Hearthstone recently updated to Unity 5, which unfortunately is not fully supported yet by https://github.com/ata4/disunity

Due to this the project is currently broken.

**Comment by Sembiance** [comment]
Currently trying to extract the latest cardxml0.unity3d file with disunity yields:

```
java -jar disunity-dist-0.4.0-SNAPSHOT.jar extract cardxml0.unity3d 
[info] DisUnity v0.4.0
[info] Processing cardxml0.unity3d
[info] Processing CAB-cardxml0
[warning] FileCommand: Can't process file cardxml0.unity3d, caused by java.io.EOFException
	at info.ata4.io.buffer.source.ReadableByteChannelSource.requestRead(ReadableByteChannelSource.java:114)
	at info.ata4.io.buffer.source.SeekableByteChannelSource.requestRead(SeekableByteChannelSource.java:150)
	at info.ata4.io.DataReader.readInt(DataReader.java:83)
	at info.ata4.unity.asset.AssetFile.loadMetadata(AssetFile.java:200)
	at info.ata4.unity.asset.AssetFile.load(AssetFile.java:136)
	at info.ata4.disunity.cli.command.AssetFileCommand.handleAssetBundleEntry(AssetFileCommand.java:82)
	at info.ata4.disunity.cli.command.AssetFileCommand.handleAssetBundleFile(AssetFileCommand.java:62)
	at info.ata4.disunity.cli.command.AssetFileCommand.handleFile(AssetFileCommand.java:48)
	at info.ata4.disunity.cli.command.FileCommand.processFile(FileCommand.java:35)
	at info.ata4.disunity.cli.command.MultiFileCommand.run(MultiFileCommand.java:54)
	at info.ata4.disunity.cli.DisUnityCli.run(DisUnityCli.java:117)
	at info.ata4.disunity.cli.DisUnityCli.main(DisUnityCli.java:131)
```

**Comment by GeminiCode** [comment]
JSON files will be still available at http://hearthstonejson.com/json/ ?

**Comment by Sembiance** [comment]
@GeminiCode Yes, files will continue to be available as they currently are.

It's just that when new cards are released I may not be able to update the JSON files.

We will see.

**Comment by hugojcastro** [comment]
I'm pretty sure you're aware about this, but just in case... ^^

@DerPopo's *Unity Assets Bundle Extractor* (https://github.com/DerPopo/UABE) is able to export text files from last Unity builds (just tested right now with latest Hearthstone client).

I guess it can be useful (at least) to keep *hearthstonejson.com* site updated, while waiting for a fix for Disunity or any other solution :)

Hope it helps ^^

**Comment by Sembiance** [comment]
Fixed. Now uses https://github.com/HearthSim/hs-data

**Comment by jshrake** [comment]
@Sembiance I'm not sure how you're extracting the data now, but you can still use disunity if you build from source (HEAD of master). I do exactly that here: https://github.com/jshrake/extracted-hearthstone-data

**Comment by jleclanche** [comment]
@jshrake We use a custom extract utility. Disunity doesn't work for everything even on master :/

Our extract scripts are here: https://github.com/hearthsim/extract-scripts

Any reason why you have that repository instead of using [hs-data](https://github.com/HearthSim/hs-data)? The latter is updated within minutes of every patch.

**Comment by jleclanche** [comment]
PS: Swing by the `#hearthsim` irc channel on freenode if you'd like to talk about this.
