### ISSUE TITLE
'CardXML' object has no attribute 'overload'

### ISSUE THREAD

**Issue by Shipow** [HearthSim/hearthstonejson#29]
I got an error with the ./generate.py

```
Traceback (most recent call last):
  File "generate.py", line 236, in <module>
    main()
  File "generate.py", line 216, in main
    export_cards_to_file(cards, filename, locale.name)
  File "generate.py", line 141, in export_cards_to_file
    ret.append(serialize_card(card))
  File "generate.py", line 109, in serialize_card
    "overload": card.overload,
AttributeError: 'CardXML' object has no attribute 'overload'
```

any idea of what i'm doing wrong?

**Comment by jleclanche** [comment]
You need to update the hearthstone library (`pip install --upgrade hearthstone`).

**Comment by Shipow** [comment]
thanks !
