### ISSUE TITLE
TypeError: unhashable type: 'collections.OrderedDict' when running generate_card_textures

### ISSUE THREAD

**Issue by sebastientromp** [HearthSim/HearthstoneJSON#75]
Hello,

I'm trying t ouse `generate_card_textures` with the following call:

`$ ./generate_card_textures.py --skip-existing --traceback --outdir textures/cards /d/Games/Hearthstone/Data/Win/{rad_base,dbf,card,cardtextures,textures,premiummaterials,shared,sounds}*.unity3d`

and I get the following error:
```
Traceback (most recent call last):
  File "./generate_card_textures.py", line 325, in <module>
    main()
  File "./generate_card_textures.py", line 285, in main
    cards, textures = extract_info(args.files, filter_ids)
  File "./generate_card_textures.py", line 117, in extract_info
    handle_asset(asset, textures, cards, filter_ids)
  File "./generate_card_textures.py", line 47, in handle_asset
    handle_rad(asset.resolve())
  File "./generate_card_textures.py", line 36, in handle_rad
    handle_rad_node("", guids, names, tree, tree[0])
  File "./generate_card_textures.py", line 25, in handle_rad_node
    guid_to_path[guid] = path + "/" + name
TypeError: unhashable type: 'collections.OrderedDict'
```

Do you have any idea what might be going wrong?

**Comment by sebastientromp** [comment]
For information, it works if I extract the `GUID` as such (L23);

```
for leaf in node["leaves"]:
		guid = guids[leaf["guidIndex"]]["GUID"]
		name = names[leaf["fileNameIndex"]]
```
